### ISSUE TITLE
Can i deploy this script to firebase free plan?

### ISSUE THREAD

**Issue by bsde1234** [vencax/netlify-cms-github-oauth-provider#18]
Can i deploy this script to firebase free plan?

**Comment by everywebco** [comment]
You can use this Netlify CMS OAuth provider as Firebase function for free:
https://github.com/Herohtar/netlify-cms-oauth-firebase

**Comment by lucbpz** [comment]
If you actually read the docs on that repo it says:

> The OAuth2 API makes external network requests which requires a Firebase project that has billing enabled. (Spark or Blaze plan)

I tried to build a setup with this repo and found this issue with Firebase, so you need to have the paid version. If you want to do it for free, this repo has worked for me: https://github.com/kpopper/netlify-serverless-oauth2-backend

Note that is is a fork from another repo, because it had an issue and this fork solves the problem 👍 .
